books/urls.py
from django.urls import path
from . import views

app_name = "books"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailsView.as_view(), name="book_details"),
    path('publishers/', views.PublisherView.as_view(), name="publishers"),
    path('publishers/<int:pk>/', views.PublisherDetailsView.as_view(), name="pub_details")
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

books/models.py
from asyncio.base_subprocess import WriteSubprocessPipeProto
from datetime import datetime, timedelta
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    country = models.CharField(max_length=60)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    website = models.URLField()

    class Meta:
        ordering = ['-name']

    def __str__(self) -> str:
        return self.name


class Author(models.Model):
    title = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    profile_pic = models.ImageField(upload_to='authors_pps')

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()
    cover = models.ImageField(upload_to='books_covers')

    def is_published_recently(self):
        return  (datetime.today() - timedelta(days=30)).date() <= self.publication_date <= datetime.today().date()

    def __str__(self) -> str:
        return self.title

books/views.py
# from django.shortcuts import render
# from django.http import HttpResponse
from urllib import request
from django.views.generic import ListView, DetailView
from .models import Book, Author, Publisher
from datetime import datetime

import books

# Create your views here.
class IndexView(ListView):
    model = Book
    context_object_name = "books_list"
    template_name = "books/index.html"

    def get_queryset(self):
        return Book.objects.filter(publication_date__lte=datetime.today().date()).order_by('-publication_date')[:5]



class DetailsView(DetailView):
    model = Book

    def get_queryset(self):
        return Book.objects.filter(pk=self.kwargs['pk'], publication_date__lte=datetime.today().date())


class PublisherView(ListView):
    model = Publisher


class PublisherDetailsView(DetailView):
    model = Publisher

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['publisher'] = self.object
        context['books_list'] = Book.objects.filter(publisher_id=self.object.id)
        return context

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header>
        <nav>This is the navigation menu</nav>
    </header>
    <div class="wrapper">
        <main>
            {% block content %}{% endblock content %}
        </main>
    </div>
    <footer>
        <p>Copy right &copy; 2022 ASeada for web development</p>
    </footer>
</body>
</html>

books/templates/books/book_detail.html
{% extends './base.html' %}
{% block title %} Book details {% endblock title%}


{% block content %} 
    <p><strong>Title:</strong>{{ book.title }}</p>
    <p><strong>Publication date:</strong>{{ book.publication_date }}</p>
    <img src={{ book.cover }}>
{% endblock content%}

books/templates/books/index.html
{% extends "./base.html" %}
{% block title %} Available Books {% endblock title %}
{% block content %}
{% if books_list %}
    <ul style="list-style-type: none;">
    {% for book in books_list %}
        <li><strong>{{ forloop.counter }}. {{ book.title }}</strong><br/>
            <strong>Authors:</strong>
            <ul>
            {% for auth in book.author.all %}
                <li> {{ auth.title }}. {{ auth.name }}</li>
            {% endfor %}
            </ul>
            <strong>Publisher: </strong>{{ book.publisher }}<br/>
            <strong>Publication date: </strong> {{ book.publication_date }}<br/>
            <strong>Cover: </strong><br/>
            <img src="../{{ book.cover }}">
        </li>
        <br/>
    {% endfor %}
    </ul>
{% else %}
    <p>No books are available</p>
{% endif %}
{% endblock content %}

books/templates/books/publisher_detail.html
{% extends './base.html' %}
{% block title %} Publisher details {% endblock title%}


{% block content %} 
    <p><strong>Name:</strong>{{ publisher.name }}</p>
    <p><strong>Country:</strong>{{ publisher.country }}</p>
    <p><strong>City: </strong>{{ publisher.city }}</p>
    <p><strong>Website: </strong><a href={{ publisher.website }}>{{ publisher.website }}</a></p>
    <p><strong>Published books:</strong></p>
    <ul>
        {% for book in books_list %}
        <li> {{ book.title }}</li>
        {% endfor %}
    </ul>
{% endblock content%}

books/templates/books/publisher_list.html
{% extends "./base.html" %}
{% block title %} Publishers List {% endblock %}
{% block content %}
<table style="margin: 20px 5px ; width: 100%;border: 1px solid;border-collapse: collapse;">
    <caption>Publishers list</caption>
    <tr style="text-align: center ;">
        <th>Publisher name</th>
    </tr>
    {% for publisher in object_list %}
    <tr style="text-align: center ;">
        <td style="border: 1px solid;"><a href="{% url 'books:pub_details' publisher.id %}">{{ publisher.name }}</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}